import { useState } from 'react';
import { Plus, Sparkles, Trash2 } from 'lucide-react';
import { api } from '../lib/api';

const empty = { title: '', description: '', evidence: '', impact: 'high', urgency: 'high', recommendation: '', priority: 75, confidence: 'medium', risk: '', commercial_impact: '', requires_validation: false, visual_status: 'yellow' };
const severityLabels = { low: 'Bajo', medium: 'Medio', high: 'Alto', critical: 'Crítico' };
const statusLabels = { green: 'Controlado', yellow: 'Inconsistente', red: 'Pérdida probable', gray: 'Sin evidencia' };

export default function DiagnosisFindings({ diagnosisId, items, onChanged }) {
  const [form, setForm] = useState(empty); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const generate = async () => { setBusy(true); setError(''); try { await api(`/api/diagnose/${diagnosisId}/generate-findings`, { method: 'POST' }); onChanged?.(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const create = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await api(`/api/diagnose/${diagnosisId}/findings`, { method: 'POST', body: JSON.stringify(form) }); setForm(empty); setShowForm(false); onChanged?.(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const update = async (item, patch) => { try { await api(`/api/diagnose/${diagnosisId}/findings/${item.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); onChanged?.(); } catch (e) { setError(e.message); } };
  const remove = async (item) => { if (!window.confirm(`Eliminar el hallazgo “${item.title}”?`)) return; try { await api(`/api/diagnose/${diagnosisId}/findings/${item.id}`, { method: 'DELETE' }); onChanged?.(); } catch (e) { setError(e.message); } };
  return <section className="diagnosis-section-stack"><div className="section-heading"><div><p className="eyebrow">HALLAZGOS</p><h2>Qué está frenando el proceso</h2><p>Conserva evidencia, riesgo, impacto comercial, confianza y advertencias de validación.</p></div><div className="section-actions"><button className="button secondary" onClick={generate} disabled={busy}><Sparkles size={16} />Generar desde bloques</button><button className="button diagnose-primary" onClick={() => setShowForm(!showForm)}><Plus size={16} />Hallazgo manual</button></div></div>{error && <div className="form-error">{error}</div>}
    {showForm && <form className="panel finding-form" onSubmit={create}><label>Hallazgo<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><div className="form-grid three"><label>Estado visual<select value={form.visual_status} onChange={(e) => setForm({ ...form, visual_status: e.target.value })}>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Confianza<select value={form.confidence} onChange={(e) => setForm({ ...form, confidence: e.target.value })}><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option></select></label><label>Impacto<select value={form.impact} onChange={(e) => setForm({ ...form, impact: e.target.value })}>{Object.entries(severityLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><label>Evidencia<textarea rows="2" value={form.evidence} onChange={(e) => setForm({ ...form, evidence: e.target.value })} /></label><div className="form-grid two"><label>Riesgo<textarea rows="3" value={form.risk} onChange={(e) => setForm({ ...form, risk: e.target.value })} /></label><label>Impacto comercial<textarea rows="3" value={form.commercial_impact} onChange={(e) => setForm({ ...form, commercial_impact: e.target.value })} /></label></div><label>Recomendación<textarea rows="3" value={form.recommendation} onChange={(e) => setForm({ ...form, recommendation: e.target.value })} /></label><label className="inline-check"><input type="checkbox" checked={form.requires_validation} onChange={(e) => setForm({ ...form, requires_validation: e.target.checked })} />Requiere validación</label><div className="form-actions"><button className="button diagnose-primary" disabled={busy}>Guardar hallazgo</button></div></form>}
    <div className="finding-list">{(items || []).map((item) => <article key={item.id} className={`finding-card ${item.impact}`}><header><div><span className={`visual-status ${item.visual_status || 'yellow'}`}>{statusLabels[item.visual_status || 'yellow']}</span><span className={`severity-pill ${item.impact}`}>{severityLabels[item.impact]}</span></div><strong>{item.priority}</strong></header><h3>{item.title}</h3>{item.evidence && <blockquote>{item.evidence}</blockquote>}<dl className="finding-structure">{item.risk && <div><dt>Riesgo</dt><dd>{item.risk}</dd></div>}{item.commercial_impact && <div><dt>Impacto comercial</dt><dd>{item.commercial_impact}</dd></div>}<div><dt>Confianza</dt><dd>{item.confidence || 'medium'}</dd></div></dl>{item.recommendation && <div className="finding-recommendation"><small>RECOMENDACIÓN</small><p>{item.recommendation}</p></div>}{item.requires_validation && <p className="validation-warning">Requiere validación antes del informe final.</p>}<footer><select value={item.status} onChange={(e) => update(item, { status: e.target.value })}><option value="open">Abierto</option><option value="sent_to_focus">Enviado a Focus</option><option value="resolved">Resuelto</option><option value="dismissed">Descartado</option></select><button className="danger-icon" onClick={() => remove(item)}><Trash2 size={16} /></button></footer></article>)}</div>
  </section>;
}
