import { useMemo, useState } from 'react';
import { CheckCircle2, Plus, Send, Sparkles, Trash2 } from 'lucide-react';
import { api } from '../lib/api';

const phases = [{ id: '7_days', label: 'Primeros 7 días' }, { id: '30_days', label: 'Próximos 30 días' }, { id: '90_days', label: 'Después de 30 días' }];
const empty = { phase: '7_days', title: '', description: '', priority: 'high', owner_id: '', due_date: '', metric: '', tool: '', compliance_evidence: '', dependency: '', recommendation_group: '30_days' };
const groupLabels = { immediate: 'Corregir inmediatamente', '30_days': 'Organizar en 30 días', later: 'Automatizar después', do_not_touch: 'No tocar todavía' };

export default function DiagnosisRoadmap({ diagnosisId, items, profiles, onChanged }) {
  const [form, setForm] = useState(empty); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const grouped = useMemo(() => Object.fromEntries(phases.map((phase) => [phase.id, (items || []).filter((item) => item.phase === phase.id)])), [items]);
  const generate = async () => { setBusy(true); setError(''); try { const result = await api(`/api/diagnose/${diagnosisId}/generate-roadmap`, { method: 'POST' }); setMessage(`${result.created} acciones agregadas.`); onChanged?.(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const create = async (event) => { event.preventDefault(); setBusy(true); try { await api(`/api/diagnose/${diagnosisId}/roadmap`, { method: 'POST', body: JSON.stringify({ ...form, owner_id: form.owner_id || null, due_date: form.due_date || null }) }); setForm(empty); setShowForm(false); onChanged?.(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const update = async (item, patch) => { try { await api(`/api/diagnose/${diagnosisId}/roadmap/${item.id}`, { method: 'PATCH', body: JSON.stringify(patch) }); onChanged?.(); } catch (e) { setError(e.message); } };
  const send = async (item) => { setBusy(true); try { await api(`/api/diagnose/${diagnosisId}/roadmap/${item.id}/send-to-focus`, { method: 'POST', body: JSON.stringify({ assigned_to: item.owner_id || null, due_date: item.due_date || null }) }); setMessage('Acción enviada a Focus.'); onChanged?.(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const remove = async (item) => { if (!window.confirm(`Eliminar la acción “${item.title}”?`)) return; try { await api(`/api/diagnose/${diagnosisId}/roadmap/${item.id}`, { method: 'DELETE' }); onChanged?.(); } catch (e) { setError(e.message); } };
  return <section className="diagnosis-section-stack"><div className="section-heading"><div><p className="eyebrow">ROADMAP</p><h2>Acciones verificables</h2><p>Cada acción debe tener responsable, plazo, métrica, herramienta y evidencia de cumplimiento.</p></div><div className="section-actions"><button className="button secondary" onClick={generate} disabled={busy}><Sparkles size={16} />Generar desde hallazgos</button><button className="button diagnose-primary" onClick={() => setShowForm(!showForm)}><Plus size={16} />Acción manual</button></div></div>{error && <div className="form-error">{error}</div>}{message && <div className="diagnose-success"><CheckCircle2 size={17} />{message}</div>}
    {showForm && <form className="panel roadmap-form" onSubmit={create}><div className="form-grid three"><label>Fase<select value={form.phase} onChange={(e) => setForm({ ...form, phase: e.target.value })}>{phases.map((p) => <option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label>Grupo<select value={form.recommendation_group} onChange={(e) => setForm({ ...form, recommendation_group: e.target.value })}>{Object.entries(groupLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Responsable<select value={form.owner_id} onChange={(e) => setForm({ ...form, owner_id: e.target.value })}><option value="">Sin asignar</option>{(profiles || []).map((p) => <option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label></div><label>Acción<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Descripción<textarea rows="2" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><div className="form-grid two"><label>Fecha objetivo<input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></label><label>Métrica<input value={form.metric} onChange={(e) => setForm({ ...form, metric: e.target.value })} /></label><label>Herramienta<input value={form.tool} onChange={(e) => setForm({ ...form, tool: e.target.value })} /></label><label>Evidencia de cumplimiento<input value={form.compliance_evidence} onChange={(e) => setForm({ ...form, compliance_evidence: e.target.value })} /></label></div><label>Dependencia<input value={form.dependency} onChange={(e) => setForm({ ...form, dependency: e.target.value })} /><div className="form-actions"><button className="button diagnose-primary">Guardar acción</button></div></label></form>}
    <div className="roadmap-timeline">{phases.map((phase) => <section key={phase.id} className="roadmap-phase"><header><span className="roadmap-dot" /><div><h3>{phase.label}</h3></div><strong>{grouped[phase.id]?.length || 0}</strong></header><div className="roadmap-items">{(grouped[phase.id] || []).map((item) => <article key={item.id} className={`roadmap-card ${item.priority}`}><div className="roadmap-card-main"><header><span className={`severity-pill ${item.priority}`}>{groupLabels[item.recommendation_group] || item.priority}</span><span>{item.due_date || 'Sin fecha'}</span></header><h4>{item.title}</h4>{item.description && <p>{item.description}</p>}<dl className="roadmap-details"><div><dt>Responsable</dt><dd>{item.owner_name || 'Sin asignar'}</dd></div><div><dt>Métrica</dt><dd>{item.metric || 'Pendiente'}</dd></div><div><dt>Herramienta</dt><dd>{item.tool || 'Pendiente'}</dd></div><div><dt>Evidencia</dt><dd>{item.compliance_evidence || 'Pendiente'}</dd></div></dl></div><div className="roadmap-card-actions"><select value={item.status} onChange={(e) => update(item, { status: e.target.value })}><option value="planned">Planificada</option><option value="sent_to_focus">En Focus</option><option value="in_progress">En progreso</option><option value="completed">Completada</option><option value="cancelled">Cancelada</option></select><button className="button small diagnose-outline" onClick={() => send(item)} disabled={busy || item.status === 'completed'}><Send size={15} />Enviar a Focus</button><button className="danger-icon" onClick={() => remove(item)}><Trash2 size={16} /></button></div></article>)}</div></section>)}</div>
  </section>;
}
